### ISSUE TITLE
gc9a01_simpletest.py Novice board,SPI() enquiry

### ISSUE THREAD

**Issue by dsssssssss9** [tylercrumpton/CircuitPython_GC9A01#1]

**Comment by dsssssssss9** [comment]
in the gc9a01_simpletest example when i run this on a Pi Pico at line#10 i get an ....

AttributeError: 'module' object has no attribute 'SPI'

is this because i am using a Pico as i cannot find board.SPI from the imported board library?

**Comment by dsssssssss9** [comment]
Seem to have answered my own question .... the Pi Pico does NOT have SPI defined in its board definition file

sorry to have troubled you

I really must look harder before bothering people!

**Comment by tylercrumpton** [comment]
No worries! Yeah, you'll want to replace that line with something like:

```spi = busio.SPI(board.GP6, board.GP7)```

and import busio at the top of your file:

```import busio```
